### ISSUE TITLE
can't start the bot after following the docs

### ISSUE THREAD

**Issue by hossnys** [threefoldtecharchive/tfgrid_monitoring_bot#6]
following steps [here](https://github.com/threefoldtech/tfgrid_monitoring_bot#to-run-the-project): run into this error 
```
:root/tfgrid_monitoring_bot$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```
trying docker image lead to this error and docker didn't start:
```
tfgrid_monitoring_bot$ docker build -t test .
Sending build context to Docker daemon  41.72MB
Step 1/8 : FROM node:16-alpine AS Build
 ---> e5065cc78074
Step 2/8 : WORKDIR /app
 ---> Running in 7691441a244a
Removing intermediate container 7691441a244a
 ---> 0a1e87d54fa6
Step 3/8 : COPY package.json ./
 ---> 5fc6cd2916d9
Step 4/8 : RUN yarn install
 ---> Running in 6aaa8218b565
yarn install v1.22.18
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.7.2" has unmet peer dependency "@polkadot/util@9.7.2".
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.7.2" has unmet peer dependency "@polkadot/util-crypto@9.7.2".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning " > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "/app/node_modules/sodium-native: Command failed.
Exit code: 1
Command: node-gyp-build \"node preinstall.js\" \"node postinstall.js\"
Arguments: 
Directory: /app/node_modules/sodium-native
Output:
libtool is required, but wasn't found on this system
./configure: line 5: ./configure: not found
/app/node_modules/sodium-native/preinstall.js:119
    if (err) throw err
             ^

Error: ./configure exited with 127
    at ChildProcess.<anonymous> (/app/node_modules/sodium-native/preinstall.js:149:25)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)"
info This module is OPTIONAL, you can safely ignore this error
success Saved lockfile.
Done in 85.12s.
Removing intermediate container 6aaa8218b565
 ---> 410996e6420e
Step 5/8 : FROM node:16-alpine
 ---> e5065cc78074
Step 6/8 : COPY --from=Build /app/node_modules ./node_modules
 ---> 4b2da3745cdb
Step 7/8 : COPY package.json app.ts .env ./
 ---> 58b8781450de
Step 8/8 : CMD ["yarn", "ts-node","app.ts"]
 ---> Running in 7f1811319edc
Removing intermediate container 7f1811319edc
 ---> 0cde3da060df
Successfully built 0cde3da060df
Successfully tagged test:latest

```
docker logs : 
```
yarn run v1.22.18
$ /node_modules/.bin/ts-node app.ts
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 9.7.2  	node_modules/ts-rmb-http-client/node_modules/@polkadot/util/cjs
	cjs 10.1.13	node_modules/@polkadot/util/cjs
@polkadot/keyring has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 9.7.2  	node_modules/ts-rmb-http-client/node_modules/@polkadot/keyring/cjs
	cjs 10.1.13	node_modules/@polkadot/keyring/cjs
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 9.7.2  	node_modules/ts-rmb-http-client/node_modules/@polkadot/util-crypto/cjs
	cjs 10.1.13	node_modules/@polkadot/util-crypto/cjs
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 9.7.2  	node_modules/ts-rmb-http-client/node_modules/@polkadot/util/cjs
	cjs 10.1.13	node_modules/@polkadot/util/cjs
	cjs 9.7.2  	node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/util/cjs
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 6.3.1	node_modules/ts-rmb-http-client/node_modules/@polkadot/wasm-crypto/cjs
	cjs 6.3.1	node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/cjs
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 6.3.1	node_modules/ts-rmb-http-client/node_modules/@polkadot/wasm-bridge/cjs
	cjs 6.3.1	node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-bridge/cjs
@polkadot/wasm-crypto-wasm has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 6.3.1	node_modules/ts-rmb-http-client/node_modules/@polkadot/wasm-crypto-wasm/cjs
	cjs 6.3.1	node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-crypto-wasm/cjs
@polkadot/wasm-util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 6.3.1	node_modules/ts-rmb-http-client/node_modules/@polkadot/wasm-util/cjs
	cjs 6.3.1	node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-util/cjs
/node_modules/tfgrid-api-client/lib/client.js:51
        throw Error('Invalid mnemonic or secret seed! Check your input.')
              ^
Error: Invalid mnemonic or secret seed! Check your input.
    at Client.init (/node_modules/tfgrid-api-client/lib/client.js:51:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TFClient.connect (/node_modules/grid3_client/dist/node/clients/tf-grid/client.js:48:13)
    at async GridClient.connect (/node_modules/grid3_client/dist/node/client.js:75:9)
    at async connect (/app.ts:36:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hossnys** [comment]
there was something wrong in .env file , so after fixing it , it was just checking against the hard-coded addresses in code [here](https://github.com/threefoldtech/tfgrid_monitoring_bot/blob/development/app.ts#L26)
